# sb-deploy-functions.ps1
# Deploys Supabase Edge Functions and sets required secrets.
# Run from project root: .\sb-deploy-functions.ps1
# Requires: Supabase CLI installed (https://supabase.com/docs/guides/cli)
#
# Secrets needed:
#   SUPABASE_SERVICE_ROLE_KEY  — from Supabase Project Settings > API > service_role key
#   VAPID_PRIVATE_KEY          — generated by generate-vapid.js
#   VAPID_PUBLIC_KEY           — same (public)
#   VAPID_SUBJECT              — mailto: address

param(
    [string]$ServiceRoleKey = "",
    [string]$ProjectRef    = "wsorngsyowgxikiepice"
)

$VAPID_PRIVATE = "JQcXeB_Am-Pyz3rGnopgA2qKtICNIQTEIoqXKyiHmr4"
$VAPID_PUBLIC  = "BLTV9C7RV2nVM9R-yQXtbfy_SfX7QmNSsA4XPZ_d3Q68ELssl0SioBz8RHjp1FxuAA_Zm2_ZcJ_tjEaRonDHEzA"
$VAPID_SUBJECT = "mailto:admin@soulciety.app"

if (-not (Get-Command supabase -ErrorAction SilentlyContinue)) {
    Write-Error "Supabase CLI not found. Install from: https://supabase.com/docs/guides/cli"
    exit 1
}

# ── Login / link project ──────────────────────────────────────────────────────
Write-Host "[1/4] Linking project $ProjectRef ..." -ForegroundColor Cyan
supabase link --project-ref $ProjectRef

# ── Set secrets ──────────────────────────────────────────────────────────────
Write-Host "[2/4] Setting secrets ..." -ForegroundColor Cyan

$secrets = @(
    "VAPID_PRIVATE_KEY=$VAPID_PRIVATE",
    "VAPID_PUBLIC_KEY=$VAPID_PUBLIC",
    "VAPID_SUBJECT=$VAPID_SUBJECT"
)

if ($ServiceRoleKey) {
    $secrets += "SUPABASE_SERVICE_ROLE_KEY=$ServiceRoleKey"
} else {
    Write-Warning "SUPABASE_SERVICE_ROLE_KEY not provided — skipping. Set it manually in Supabase Dashboard > Settings > Edge Functions."
}

foreach ($s in $secrets) {
    $name = $s.Split('=')[0]
    Write-Host "  Setting $name ..." -ForegroundColor Gray
    supabase secrets set $s
}

# ── Deploy function ───────────────────────────────────────────────────────────
Write-Host "[3/4] Deploying send-notifications Edge Function ..." -ForegroundColor Cyan
supabase functions deploy send-notifications --no-verify-jwt

# ── Verify ───────────────────────────────────────────────────────────────────
Write-Host "[4/4] Done. Verifying function list ..." -ForegroundColor Cyan
supabase functions list

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host " Edge Function deployed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host " IMPORTANT — Run this SQL in Supabase SQL Editor if you" -ForegroundColor Yellow
Write-Host " haven't already (supabase/migrate-notifications.sql)" -ForegroundColor Yellow
Write-Host " to enable pg_cron job that calls this function every minute." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Green
